CREATE DATABASE clientlab;
USE clientlab;

CREATE TABLE tb_cliente_pf(
	ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY
    ,NOME_CLIENTE VARCHAR(100) NOT NULL
    ,ENDERECO VARCHAR(100) NOT NULL
    ,CPF VARCHAR(14)
    ,RG VARCHAR(12)
);

CREATE TABLE tb_cliente_pj(
	ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY
    ,NOME_CLIENTE VARCHAR(100) NOT NULL
    ,ENDERECO VARCHAR(100) NOT NULL
    ,CNPJ VARCHAR(18)
    ,IE VARCHAR(20)
);

CREATE TABLE tb_vendas(
	ID_VENDA INT AUTO_INCREMENT PRIMARY KEY
    ,FK_CLIENTE_PF INT
    ,FK_CLIENTE_PJ INT
    ,VALOR_COMPRA DOUBLE 
    ,VALOR_IMPOSTO DOUBLE
    ,VALOR_TOTAL DOUBLE
    ,FOREIGN KEY (FK_CLIENTE_PF) REFERENCES tb_cliente_pf(ID_CLIENTE)
    ,FOREIGN KEY (FK_CLIENTE_PJ) REFERENCES tb_cliente_pj(ID_CLIENTE)
)